name: Sync to Gitee

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Gitee remote and push
        run: |
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_TOKEN }}@gitee.com/kkcoco/dsh-monitor.git
          git push gitee --all --force
          git push gitee --tags --force
