name: Sync to Gitee

on:
  push:
    branches: [ '**' ]
    tags: [ '**' ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整历史，包含所有 tag

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/kkcoco
          dst: gitee/kkcoco
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "dsh-monitor"
          force_update: true
          debug: true
